<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Post-secondary Paths CART – Pathways taken after high school - Southern</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-c1fac2584b48ed01fb6e278e36375074.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="site_libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">
<script src="site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="site_libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="site_libs/datatables-binding-0.33/datatables.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>
<link href="site_libs/nouislider-7.0.10/jquery.nouislider.min.css" rel="stylesheet">
<script src="site_libs/nouislider-7.0.10/jquery.nouislider.min.js"></script>
<link href="site_libs/selectize-0.12.0/selectize.bootstrap3.css" rel="stylesheet">
<script src="site_libs/selectize-0.12.0/selectize.min.js"></script>
<link href="site_libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet">
<script src="site_libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Pathways taken after high school - Southern</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Summary</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-data-prep-and-summaries" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-fa-gear" role="img">
</i> 
 <span class="menu-text">Data Prep and Summaries</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-data-prep-and-summaries">    
        <li>
    <a class="dropdown-item" href="./k12enrollment.html">
 <span class="dropdown-text">K12Enrollment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./k12orgs.html">
 <span class="dropdown-text">K12Orgs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./act.html">
 <span class="dropdown-text">ACT</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ap.html">
 <span class="dropdown-text">AP</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./cteenrollment.html">
 <span class="dropdown-text">CTEEnrollment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ctedemographics.html">
 <span class="dropdown-text">CTEDemographics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./assessments.html">
 <span class="dropdown-text">Assessments</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./sat.html">
 <span class="dropdown-text">SAT</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nscenrollment.html">
 <span class="dropdown-text">National Student Clearinghouse - Enrollment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nsccompletions.html">
 <span class="dropdown-text">National Student Clearinghouse - Completions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./employment.html">
 <span class="dropdown-text">Employment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./emp_states_each_year.html">
 <span class="dropdown-text">Employment states each year</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./unemployment.html">
 <span class="dropdown-text">Unemployment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./avgwages.html">
 <span class="dropdown-text">Average wages</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-analysis" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-fa-gear" role="img">
</i> 
 <span class="menu-text">Analysis</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-analysis">    
        <li>
    <a class="dropdown-item" href="./analysis_mca.html">
 <span class="dropdown-text">Multiple Correspondence Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_dep_var_states.html">
 <span class="dropdown-text">Dependent Variable States</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_local_employment_ct.html">
 <span class="dropdown-text">Local Employment Cross-tabs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_post_secondary_pathways_ct.qmd">
 <span class="dropdown-text">Post-secondary pathways cross-tabs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_local_employment_CART.html">
 <span class="dropdown-text">Local Employment CART Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_post_secondary_paths_CART.html">
 <span class="dropdown-text">Post-secondary pathways CART</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_non_post_secondary_graduates.html">
 <span class="dropdown-text">Non-college graduates</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#post-secondary-paths" id="toc-post-secondary-paths" class="nav-link active" data-scroll-target="#post-secondary-paths">Post-secondary Paths</a>
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#dependent-variables" id="toc-dependent-variables" class="nav-link" data-scroll-target="#dependent-variables">Dependent variables</a>
  <ul class="collapse">
  <li><a href="#dependent-variable-recoding-for-cart-analysis" id="toc-dependent-variable-recoding-for-cart-analysis" class="nav-link" data-scroll-target="#dependent-variable-recoding-for-cart-analysis">Dependent Variable Recoding for CART Analysis</a></li>
  </ul></li>
  <li><a href="#independent-variables" id="toc-independent-variables" class="nav-link" data-scroll-target="#independent-variables">Independent Variables</a>
  <ul class="collapse">
  <li><a href="#demographics" id="toc-demographics" class="nav-link" data-scroll-target="#demographics">1. Demographics</a></li>
  <li><a href="#high-school-characteristics" id="toc-high-school-characteristics" class="nav-link" data-scroll-target="#high-school-characteristics">2. High School Characteristics</a></li>
  <li><a href="#high-school-accomplishments" id="toc-high-school-accomplishments" class="nav-link" data-scroll-target="#high-school-accomplishments">3. High School Accomplishments</a></li>
  <li><a href="#de-prioritize-drop" id="toc-de-prioritize-drop" class="nav-link" data-scroll-target="#de-prioritize-drop">De-prioritize / Drop</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology">Methodology</a></li>
  <li><a href="#analysis---post-secondary-location" id="toc-analysis---post-secondary-location" class="nav-link" data-scroll-target="#analysis---post-secondary-location">Analysis - Post secondary location</a>
  <ul class="collapse">
  <li><a href="#base-model" id="toc-base-model" class="nav-link" data-scroll-target="#base-model">Base Model</a></li>
  <li><a href="#pre-pruning" id="toc-pre-pruning" class="nav-link" data-scroll-target="#pre-pruning">Pre-pruning</a></li>
  <li><a href="#post-pruning" id="toc-post-pruning" class="nav-link" data-scroll-target="#post-pruning">Post-pruning</a></li>
  <li><a href="#main-takeaway" id="toc-main-takeaway" class="nav-link" data-scroll-target="#main-takeaway"><strong>Main Takeaway</strong></a></li>
  </ul></li>
  <li><a href="#analysis---highest-credential-earned" id="toc-analysis---highest-credential-earned" class="nav-link" data-scroll-target="#analysis---highest-credential-earned">Analysis - Highest Credential Earned</a>
  <ul class="collapse">
  <li><a href="#base-model-1" id="toc-base-model-1" class="nav-link" data-scroll-target="#base-model-1">Base Model</a></li>
  <li><a href="#pre-pruning-1" id="toc-pre-pruning-1" class="nav-link" data-scroll-target="#pre-pruning-1">Pre-pruning</a></li>
  <li><a href="#post-pruning-1" id="toc-post-pruning-1" class="nav-link" data-scroll-target="#post-pruning-1">Post-pruning</a></li>
  <li><a href="#main-takeaway-1" id="toc-main-takeaway-1" class="nav-link" data-scroll-target="#main-takeaway-1"><strong>Main Takeaway</strong></a></li>
  </ul></li>
  <li><a href="#grand-synthesis-predictive-elements-of-postsecondary-pathways" id="toc-grand-synthesis-predictive-elements-of-postsecondary-pathways" class="nav-link" data-scroll-target="#grand-synthesis-predictive-elements-of-postsecondary-pathways"><strong>Grand Synthesis: Predictive Elements of Postsecondary Pathways</strong></a>
  <ul class="collapse">
  <li><a href="#overall-model-performance" id="toc-overall-model-performance" class="nav-link" data-scroll-target="#overall-model-performance"><strong>Overall Model Performance</strong></a></li>
  <li><a href="#key-predictors-across-models" id="toc-key-predictors-across-models" class="nav-link" data-scroll-target="#key-predictors-across-models"><strong>Key Predictors Across Models</strong></a></li>
  <li><a href="#interpretation-of-pathways" id="toc-interpretation-of-pathways" class="nav-link" data-scroll-target="#interpretation-of-pathways"><strong>Interpretation of Pathways</strong></a>
  <ul class="collapse">
  <li><a href="#graduation-location-ps.grad.location" id="toc-graduation-location-ps.grad.location" class="nav-link" data-scroll-target="#graduation-location-ps.grad.location">1. <strong>Graduation Location (ps.grad.location)</strong></a></li>
  <li><a href="#highest-credential-earned-highest.cred.level-1" id="toc-highest-credential-earned-highest.cred.level-1" class="nav-link" data-scroll-target="#highest-credential-earned-highest.cred.level-1">2. <strong>Highest Credential Earned (highest.cred.level)</strong></a></li>
  </ul></li>
  <li><a href="#synthesis-of-findings" id="toc-synthesis-of-findings" class="nav-link" data-scroll-target="#synthesis-of-findings"><strong>Synthesis of Findings</strong></a></li>
  <li><a href="#policy-implications" id="toc-policy-implications" class="nav-link" data-scroll-target="#policy-implications"><strong>Policy Implications</strong></a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><strong>Conclusion</strong></a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Post-secondary Paths CART</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>master.original <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Data/SLEDS/Masters/After analysis/Master-after-ct.csv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ps.grad.InstitutionSector =</span> <span class="fu">ifelse</span>(ps.grad.InstitutionSector <span class="sc">==</span> <span class="st">"1"</span>, <span class="st">"Public, 4-year"</span>, <span class="fu">as.character</span>(ps.grad.InstitutionSector)),</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">ps.grad.InstitutionSector =</span> <span class="fu">ifelse</span>(ps.grad.InstitutionSector <span class="sc">==</span> <span class="st">"4"</span>, <span class="st">"Public, 2-year"</span>, <span class="fu">as.character</span>(ps.grad.InstitutionSector)),</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">ps.grad.InstitutionSector =</span> <span class="fu">ifelse</span>(ps.grad.InstitutionSector <span class="sc">==</span> <span class="st">"11"</span>, <span class="st">"Other"</span>, <span class="fu">as.character</span>(ps.grad.InstitutionSector)),</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">ps.grad.location =</span> <span class="fu">ifelse</span>(ps.grad.location <span class="sc">==</span> <span class="st">"PS grad EDR"</span>, <span class="st">"PS grad region"</span>, ps.grad.location),</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">highest.cred.level =</span> <span class="fu">as.factor</span>(highest.cred.level),</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">ps.grad.location =</span> <span class="fu">as.factor</span>(ps.grad.location))</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">names</span>(master.original))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PersonID</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dem_Desc</td>
</tr>
<tr class="odd">
<td style="text-align: left;">edr</td>
</tr>
<tr class="even">
<td style="text-align: left;">grad.year.covid</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gender</td>
</tr>
<tr class="even">
<td style="text-align: left;">economic.status</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pseo.participant</td>
</tr>
<tr class="even">
<td style="text-align: left;">SpecialEdStatus</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RaceEthnicity</td>
</tr>
<tr class="even">
<td style="text-align: left;">cte.achievement</td>
</tr>
<tr class="odd">
<td style="text-align: left;">attended.ps</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.InstitutionSector</td>
</tr>
<tr class="even">
<td style="text-align: left;">highest.cred.level</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.location</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.in.same.ruca</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.in.same.edr</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.in.same.pr</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.in.MN</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACTCompositeScore</td>
</tr>
<tr class="odd">
<td style="text-align: left;">total.cte.courses.taken</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACTE.SPED</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Agriculture..Food..and.Natural.Resources</td>
</tr>
<tr class="even">
<td style="text-align: left;">Architecture…Construction</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Arts..A.V.Technology…Communication</td>
</tr>
<tr class="even">
<td style="text-align: left;">Business..Management…Administrative</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Diversified</td>
</tr>
<tr class="even">
<td style="text-align: left;">Education…Training</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Finance</td>
</tr>
<tr class="even">
<td style="text-align: left;">Government…Public.Administration</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Health.Science</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hospitality…Tourism</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Human.Services</td>
</tr>
<tr class="even">
<td style="text-align: left;">Information.Technology</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Law..Public.Safety…Security</td>
</tr>
<tr class="even">
<td style="text-align: left;">Manufacturing</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Marketing</td>
</tr>
<tr class="even">
<td style="text-align: left;">Program.Area..Diversified.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Science..Technology..Engineering….Mathematics</td>
</tr>
<tr class="even">
<td style="text-align: left;">STEM</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Transportation..Distribution…Logistics</td>
</tr>
<tr class="even">
<td style="text-align: left;">Work.Experience.Handicapped</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Work.Experience.Handicapped..16.20..on.IEP.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Work.Experience.Career.Exploration..age.14.15.on.I</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Work.Experience.Disadvantaged</td>
</tr>
<tr class="even">
<td style="text-align: left;">Youth.Apprenticeship</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MCA.M</td>
</tr>
<tr class="even">
<td style="text-align: left;">MCA.R</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MCA.S</td>
</tr>
<tr class="even">
<td style="text-align: left;">n.institutions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">avg.unemp.rate</td>
</tr>
<tr class="even">
<td style="text-align: left;">wages.3year.avg</td>
</tr>
<tr class="odd">
<td style="text-align: left;">avg.wages.pct.state</td>
</tr>
<tr class="even">
<td style="text-align: left;">grad.year.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grad.year.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">grad.year.10</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(master.original))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 0%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">PersonID</th>
<th style="text-align: left;">Dem_Desc</th>
<th style="text-align: left;">edr</th>
<th style="text-align: left;">grad.year.covid</th>
<th style="text-align: left;">Gender</th>
<th style="text-align: right;">economic.status</th>
<th style="text-align: right;">pseo.participant</th>
<th style="text-align: right;">SpecialEdStatus</th>
<th style="text-align: left;">RaceEthnicity</th>
<th style="text-align: left;">cte.achievement</th>
<th style="text-align: left;">attended.ps</th>
<th style="text-align: left;">ps.grad</th>
<th style="text-align: left;">ps.grad.InstitutionSector</th>
<th style="text-align: left;">highest.cred.level</th>
<th style="text-align: left;">ps.grad.location</th>
<th style="text-align: left;">ps.grad.in.same.ruca</th>
<th style="text-align: left;">ps.grad.in.same.edr</th>
<th style="text-align: left;">ps.grad.in.same.pr</th>
<th style="text-align: left;">ps.grad.in.MN</th>
<th style="text-align: right;">ACTCompositeScore</th>
<th style="text-align: right;">total.cte.courses.taken</th>
<th style="text-align: right;">ACTE.SPED</th>
<th style="text-align: right;">Agriculture..Food..and.Natural.Resources</th>
<th style="text-align: right;">Architecture…Construction</th>
<th style="text-align: right;">Arts..A.V.Technology…Communication</th>
<th style="text-align: right;">Business..Management…Administrative</th>
<th style="text-align: right;">Diversified</th>
<th style="text-align: right;">Education…Training</th>
<th style="text-align: right;">Finance</th>
<th style="text-align: right;">Government…Public.Administration</th>
<th style="text-align: right;">Health.Science</th>
<th style="text-align: right;">Hospitality…Tourism</th>
<th style="text-align: right;">Human.Services</th>
<th style="text-align: right;">Information.Technology</th>
<th style="text-align: right;">Law..Public.Safety…Security</th>
<th style="text-align: right;">Manufacturing</th>
<th style="text-align: right;">Marketing</th>
<th style="text-align: right;">Program.Area..Diversified.</th>
<th style="text-align: right;">Science..Technology..Engineering….Mathematics</th>
<th style="text-align: right;">STEM</th>
<th style="text-align: right;">Transportation..Distribution…Logistics</th>
<th style="text-align: right;">Work.Experience.Handicapped</th>
<th style="text-align: right;">Work.Experience.Handicapped..16.20..on.IEP.</th>
<th style="text-align: right;">Work.Experience.Career.Exploration..age.14.15.on.I</th>
<th style="text-align: right;">Work.Experience.Disadvantaged</th>
<th style="text-align: right;">Youth.Apprenticeship</th>
<th style="text-align: right;">MCA.M</th>
<th style="text-align: right;">MCA.R</th>
<th style="text-align: right;">MCA.S</th>
<th style="text-align: right;">n.institutions</th>
<th style="text-align: right;">avg.unemp.rate</th>
<th style="text-align: right;">wages.3year.avg</th>
<th style="text-align: right;">avg.wages.pct.state</th>
<th style="text-align: left;">grad.year.1</th>
<th style="text-align: left;">grad.year.5</th>
<th style="text-align: left;">grad.year.10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">7699638</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">EDR 10 - Southeast</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">M</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Did not grad</td>
<td style="text-align: left;">Some college</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4.600000</td>
<td style="text-align: right;">42296.67</td>
<td style="text-align: right;">0.8566529</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">After 2023</td>
</tr>
<tr class="even">
<td style="text-align: right;">2225025</td>
<td style="text-align: left;">Entirely urban</td>
<td style="text-align: left;">EDR 10 - Southeast</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">M</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">No CTE</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Did not grad</td>
<td style="text-align: left;">Some college</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.900000</td>
<td style="text-align: right;">52341.33</td>
<td style="text-align: right;">0.9991283</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Not meaningful, not attending ps</td>
<td style="text-align: left;">After 2023</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10400093</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">EDR 10 - Southeast</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Y</td>
<td style="text-align: left;">Other</td>
<td style="text-align: left;">Bachelor degree or higher</td>
<td style="text-align: left;">PS grad MN</td>
<td style="text-align: left;">In same RUCA</td>
<td style="text-align: left;">Outside EDR</td>
<td style="text-align: left;">Outside PR</td>
<td style="text-align: left;">In MN</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4.666667</td>
<td style="text-align: right;">45356.67</td>
<td style="text-align: right;">0.9438229</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Meaningful emp region</td>
<td style="text-align: left;">After 2023</td>
</tr>
<tr class="even">
<td style="text-align: right;">8786746</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">EDR 10 - Southeast</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Y</td>
<td style="text-align: left;">Other</td>
<td style="text-align: left;">Less than Associate Degree</td>
<td style="text-align: left;">PS grad region</td>
<td style="text-align: left;">In same RUCA</td>
<td style="text-align: left;">Outside EDR</td>
<td style="text-align: left;">In same PR</td>
<td style="text-align: left;">In MN</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.666667</td>
<td style="text-align: right;">42372.67</td>
<td style="text-align: right;">0.8817291</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Meaningful emp region</td>
<td style="text-align: left;">After 2023</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11122574</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">EDR 10 - Southeast</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">No CTE</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Y</td>
<td style="text-align: left;">Other</td>
<td style="text-align: left;">Bachelor degree or higher</td>
<td style="text-align: left;">PS grad region</td>
<td style="text-align: left;">In same RUCA</td>
<td style="text-align: left;">Inside and outside same EDR</td>
<td style="text-align: left;">Inside and outside same PR</td>
<td style="text-align: left;">In MN</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">6.000000</td>
<td style="text-align: right;">37203.33</td>
<td style="text-align: right;">0.8676488</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Meaningful emp MN</td>
<td style="text-align: left;">Meaningful emp MN</td>
</tr>
<tr class="even">
<td style="text-align: right;">10181573</td>
<td style="text-align: left;">Entirely urban</td>
<td style="text-align: left;">EDR 10 - Southeast</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">M</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Y</td>
<td style="text-align: left;">Other</td>
<td style="text-align: left;">Bachelor degree or higher</td>
<td style="text-align: left;">PS grad MN</td>
<td style="text-align: left;">Inside and outside same RUCA</td>
<td style="text-align: left;">Outside EDR</td>
<td style="text-align: left;">Outside PR</td>
<td style="text-align: left;">In MN</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">5.466667</td>
<td style="text-align: right;">43477.33</td>
<td style="text-align: right;">1.0312134</td>
<td style="text-align: left;">Not meaningful, not attending ps</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Meaningful emp MN</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="post-secondary-paths" class="level1">
<h1>Post-secondary Paths</h1>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>The previous analyses established two central findings. First, <strong>postsecondary experiences are the strongest predictors of long-term employment outcomes in Southern Minnesota</strong>. Where students graduate, whether they complete, the type of institution, and the level of credential earned all consistently shape whether they find meaningful regional employment, move elsewhere, or become disconnected. Second, these postsecondary outcomes are not random; they are strongly conditioned by <strong>demographic background, high school context, and student accomplishments</strong>. In other words, the very pathways that most influence employment are themselves patterned by earlier characteristics.</p>
<p>Taken together, this creates a <strong>dual-pipeline system</strong>. On one side, <strong>CTE engagement, 2-year institutions, and sub-baccalaureate completions</strong> anchor students to the regional workforce, disproportionately drawing from low-income, special education, and rural backgrounds. On the other side, <strong>academic rigor and 4-year+ pathways</strong> open doors to mobility, with higher-scoring and advantaged students more likely to pursue degrees outside the region and build careers beyond Southern Minnesota.</p>
<p>This new stage of analysis turns from relationships to <strong>prediction</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>master <span class="ot">&lt;-</span> master.original <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ps.grad.location.new =</span> <span class="fu">ifelse</span>(ps.grad.location <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"PS grad MN"</span>, <span class="st">"PS grad outside MN"</span>), <span class="st">"PS grad outside region"</span>, <span class="fu">as.character</span>(ps.grad.location)),</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">highest.cred.level.new =</span> <span class="fu">ifelse</span>(highest.cred.level <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Associate degree"</span>, <span class="st">"Less than Associate Degree"</span>), <span class="st">"Associate degree or lower"</span>, <span class="fu">as.character</span>(highest.cred.level)),</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">highest.cred.level.new =</span> <span class="fu">ifelse</span>(highest.cred.level.new <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"No college"</span>, <span class="st">"Some college"</span>), <span class="st">"Did not graduate ps"</span>, <span class="fu">as.character</span>(highest.cred.level.new)))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">names</span>(master))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PersonID</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dem_Desc</td>
</tr>
<tr class="odd">
<td style="text-align: left;">edr</td>
</tr>
<tr class="even">
<td style="text-align: left;">grad.year.covid</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gender</td>
</tr>
<tr class="even">
<td style="text-align: left;">economic.status</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pseo.participant</td>
</tr>
<tr class="even">
<td style="text-align: left;">SpecialEdStatus</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RaceEthnicity</td>
</tr>
<tr class="even">
<td style="text-align: left;">cte.achievement</td>
</tr>
<tr class="odd">
<td style="text-align: left;">attended.ps</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.InstitutionSector</td>
</tr>
<tr class="even">
<td style="text-align: left;">highest.cred.level</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.location</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.in.same.ruca</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.in.same.edr</td>
</tr>
<tr class="even">
<td style="text-align: left;">ps.grad.in.same.pr</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.in.MN</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACTCompositeScore</td>
</tr>
<tr class="odd">
<td style="text-align: left;">total.cte.courses.taken</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACTE.SPED</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Agriculture..Food..and.Natural.Resources</td>
</tr>
<tr class="even">
<td style="text-align: left;">Architecture…Construction</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Arts..A.V.Technology…Communication</td>
</tr>
<tr class="even">
<td style="text-align: left;">Business..Management…Administrative</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Diversified</td>
</tr>
<tr class="even">
<td style="text-align: left;">Education…Training</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Finance</td>
</tr>
<tr class="even">
<td style="text-align: left;">Government…Public.Administration</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Health.Science</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hospitality…Tourism</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Human.Services</td>
</tr>
<tr class="even">
<td style="text-align: left;">Information.Technology</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Law..Public.Safety…Security</td>
</tr>
<tr class="even">
<td style="text-align: left;">Manufacturing</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Marketing</td>
</tr>
<tr class="even">
<td style="text-align: left;">Program.Area..Diversified.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Science..Technology..Engineering….Mathematics</td>
</tr>
<tr class="even">
<td style="text-align: left;">STEM</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Transportation..Distribution…Logistics</td>
</tr>
<tr class="even">
<td style="text-align: left;">Work.Experience.Handicapped</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Work.Experience.Handicapped..16.20..on.IEP.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Work.Experience.Career.Exploration..age.14.15.on.I</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Work.Experience.Disadvantaged</td>
</tr>
<tr class="even">
<td style="text-align: left;">Youth.Apprenticeship</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MCA.M</td>
</tr>
<tr class="even">
<td style="text-align: left;">MCA.R</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MCA.S</td>
</tr>
<tr class="even">
<td style="text-align: left;">n.institutions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">avg.unemp.rate</td>
</tr>
<tr class="even">
<td style="text-align: left;">wages.3year.avg</td>
</tr>
<tr class="odd">
<td style="text-align: left;">avg.wages.pct.state</td>
</tr>
<tr class="even">
<td style="text-align: left;">grad.year.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grad.year.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">grad.year.10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.location.new</td>
</tr>
<tr class="even">
<td style="text-align: left;">highest.cred.level.new</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(master))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 0%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">PersonID</th>
<th style="text-align: left;">Dem_Desc</th>
<th style="text-align: left;">edr</th>
<th style="text-align: left;">grad.year.covid</th>
<th style="text-align: left;">Gender</th>
<th style="text-align: right;">economic.status</th>
<th style="text-align: right;">pseo.participant</th>
<th style="text-align: right;">SpecialEdStatus</th>
<th style="text-align: left;">RaceEthnicity</th>
<th style="text-align: left;">cte.achievement</th>
<th style="text-align: left;">attended.ps</th>
<th style="text-align: left;">ps.grad</th>
<th style="text-align: left;">ps.grad.InstitutionSector</th>
<th style="text-align: left;">highest.cred.level</th>
<th style="text-align: left;">ps.grad.location</th>
<th style="text-align: left;">ps.grad.in.same.ruca</th>
<th style="text-align: left;">ps.grad.in.same.edr</th>
<th style="text-align: left;">ps.grad.in.same.pr</th>
<th style="text-align: left;">ps.grad.in.MN</th>
<th style="text-align: right;">ACTCompositeScore</th>
<th style="text-align: right;">total.cte.courses.taken</th>
<th style="text-align: right;">ACTE.SPED</th>
<th style="text-align: right;">Agriculture..Food..and.Natural.Resources</th>
<th style="text-align: right;">Architecture…Construction</th>
<th style="text-align: right;">Arts..A.V.Technology…Communication</th>
<th style="text-align: right;">Business..Management…Administrative</th>
<th style="text-align: right;">Diversified</th>
<th style="text-align: right;">Education…Training</th>
<th style="text-align: right;">Finance</th>
<th style="text-align: right;">Government…Public.Administration</th>
<th style="text-align: right;">Health.Science</th>
<th style="text-align: right;">Hospitality…Tourism</th>
<th style="text-align: right;">Human.Services</th>
<th style="text-align: right;">Information.Technology</th>
<th style="text-align: right;">Law..Public.Safety…Security</th>
<th style="text-align: right;">Manufacturing</th>
<th style="text-align: right;">Marketing</th>
<th style="text-align: right;">Program.Area..Diversified.</th>
<th style="text-align: right;">Science..Technology..Engineering….Mathematics</th>
<th style="text-align: right;">STEM</th>
<th style="text-align: right;">Transportation..Distribution…Logistics</th>
<th style="text-align: right;">Work.Experience.Handicapped</th>
<th style="text-align: right;">Work.Experience.Handicapped..16.20..on.IEP.</th>
<th style="text-align: right;">Work.Experience.Career.Exploration..age.14.15.on.I</th>
<th style="text-align: right;">Work.Experience.Disadvantaged</th>
<th style="text-align: right;">Youth.Apprenticeship</th>
<th style="text-align: right;">MCA.M</th>
<th style="text-align: right;">MCA.R</th>
<th style="text-align: right;">MCA.S</th>
<th style="text-align: right;">n.institutions</th>
<th style="text-align: right;">avg.unemp.rate</th>
<th style="text-align: right;">wages.3year.avg</th>
<th style="text-align: right;">avg.wages.pct.state</th>
<th style="text-align: left;">grad.year.1</th>
<th style="text-align: left;">grad.year.5</th>
<th style="text-align: left;">grad.year.10</th>
<th style="text-align: left;">ps.grad.location.new</th>
<th style="text-align: left;">highest.cred.level.new</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">7699638</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">EDR 10 - Southeast</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">M</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Did not grad</td>
<td style="text-align: left;">Some college</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4.600000</td>
<td style="text-align: right;">42296.67</td>
<td style="text-align: right;">0.8566529</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">Did not graduate ps</td>
</tr>
<tr class="even">
<td style="text-align: right;">2225025</td>
<td style="text-align: left;">Entirely urban</td>
<td style="text-align: left;">EDR 10 - Southeast</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">M</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">No CTE</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Did not grad</td>
<td style="text-align: left;">Some college</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.900000</td>
<td style="text-align: right;">52341.33</td>
<td style="text-align: right;">0.9991283</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Not meaningful, not attending ps</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">Did not graduate ps</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10400093</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">EDR 10 - Southeast</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Y</td>
<td style="text-align: left;">Other</td>
<td style="text-align: left;">Bachelor degree or higher</td>
<td style="text-align: left;">PS grad MN</td>
<td style="text-align: left;">In same RUCA</td>
<td style="text-align: left;">Outside EDR</td>
<td style="text-align: left;">Outside PR</td>
<td style="text-align: left;">In MN</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4.666667</td>
<td style="text-align: right;">45356.67</td>
<td style="text-align: right;">0.9438229</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Meaningful emp region</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">PS grad outside region</td>
<td style="text-align: left;">Bachelor degree or higher</td>
</tr>
<tr class="even">
<td style="text-align: right;">8786746</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">EDR 10 - Southeast</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Y</td>
<td style="text-align: left;">Other</td>
<td style="text-align: left;">Less than Associate Degree</td>
<td style="text-align: left;">PS grad region</td>
<td style="text-align: left;">In same RUCA</td>
<td style="text-align: left;">Outside EDR</td>
<td style="text-align: left;">In same PR</td>
<td style="text-align: left;">In MN</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.666667</td>
<td style="text-align: right;">42372.67</td>
<td style="text-align: right;">0.8817291</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Meaningful emp region</td>
<td style="text-align: left;">After 2023</td>
<td style="text-align: left;">PS grad region</td>
<td style="text-align: left;">Associate degree or lower</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11122574</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: left;">EDR 10 - Southeast</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">No CTE</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Y</td>
<td style="text-align: left;">Other</td>
<td style="text-align: left;">Bachelor degree or higher</td>
<td style="text-align: left;">PS grad region</td>
<td style="text-align: left;">In same RUCA</td>
<td style="text-align: left;">Inside and outside same EDR</td>
<td style="text-align: left;">Inside and outside same PR</td>
<td style="text-align: left;">In MN</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">6.000000</td>
<td style="text-align: right;">37203.33</td>
<td style="text-align: right;">0.8676488</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Meaningful emp MN</td>
<td style="text-align: left;">Meaningful emp MN</td>
<td style="text-align: left;">PS grad region</td>
<td style="text-align: left;">Bachelor degree or higher</td>
</tr>
<tr class="even">
<td style="text-align: right;">10181573</td>
<td style="text-align: left;">Entirely urban</td>
<td style="text-align: left;">EDR 10 - Southeast</td>
<td style="text-align: left;">Pre-covid grad</td>
<td style="text-align: left;">M</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Y</td>
<td style="text-align: left;">Other</td>
<td style="text-align: left;">Bachelor degree or higher</td>
<td style="text-align: left;">PS grad MN</td>
<td style="text-align: left;">Inside and outside same RUCA</td>
<td style="text-align: left;">Outside EDR</td>
<td style="text-align: left;">Outside PR</td>
<td style="text-align: left;">In MN</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">5.466667</td>
<td style="text-align: right;">43477.33</td>
<td style="text-align: right;">1.0312134</td>
<td style="text-align: left;">Not meaningful, not attending ps</td>
<td style="text-align: left;">Attending ps</td>
<td style="text-align: left;">Meaningful emp MN</td>
<td style="text-align: left;">PS grad outside region</td>
<td style="text-align: left;">Bachelor degree or higher</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br></p>
</section>
<section id="dependent-variables" class="level2">
<h2 class="anchored" data-anchor-id="dependent-variables">Dependent variables</h2>
<ol type="1">
<li><strong><code>ps.grad.location</code></strong>
<ul>
<li>Strongest predictor of regional employment.</li>
<li>Distinguishes clearly between <strong>Southern MN completers (anchored locally)</strong> and <strong>out-of-region completers (mobile/disconnected)</strong>.</li>
<li>Key to understanding <strong>who stays and who leaves</strong>.</li>
</ul></li>
<li><strong><code>highest.cred.level</code></strong>
<ul>
<li>Clearest stratifier of opportunity: <strong>associate/sub-associate = regional employment</strong>, <strong>bachelor’s+ = mobility</strong>.</li>
<li>Provides a direct lens into how educational attainment maps onto workforce outcomes.</li>
<li>Crucial for policy since it reveals the “tipping point” between staying and leaving.</li>
</ul></li>
<li><strong><code>ps.grad.InstitutionSector</code></strong>
<ul>
<li>Distinguishes <strong>public 2-year vs.&nbsp;4-year pathways</strong>.</li>
<li>Important because <strong>2-year grads disproportionately fuel the regional workforce</strong>, while 4-year grads drive mobility.</li>
<li>Adds nuance to the credential level analysis.</li>
</ul></li>
<li><strong><code>ps.grad</code></strong>
<ul>
<li>Foundational but broad: simply shows completion vs.&nbsp;non-completion.</li>
<li>Powerful predictor of avoiding disconnection, but less detailed than the other three.</li>
<li>Best treated as a baseline lens that underpins the others.</li>
</ul></li>
</ol>
<p>For this, I’m going to use the first two.</p>
<p><br></p>
<section id="dependent-variable-recoding-for-cart-analysis" class="level3">
<h3 class="anchored" data-anchor-id="dependent-variable-recoding-for-cart-analysis">Dependent Variable Recoding for CART Analysis</h3>
<p>To improve interpretability of the CART results, the original postsecondary outcome variables were recoded into fewer, conceptually meaningful categories. This ensures the models capture the key distinctions that matter most for workforce pathways without being diluted by overly granular categories.</p>
<section id="postsecondary-graduation-location-ps.grad.location" class="level4">
<h4 class="anchored" data-anchor-id="postsecondary-graduation-location-ps.grad.location">1. Postsecondary Graduation Location (<code>ps.grad.location</code>)</h4>
<ul>
<li><strong>Original categories</strong>:
<ul>
<li>PS grad region</li>
<li>PS grad MN</li>
<li>PS grad outside MN</li>
<li>Did not graduate PS</li>
<li>Attending PS</li>
</ul></li>
<li><strong>Recoding approach</strong>:
<ul>
<li>Excluded <em>Attending PS</em> to focus on completed vs.&nbsp;non-completed pathways.</li>
<li>Collapsed <em>PS grad MN</em> and <em>PS grad outside MN</em> into a single category: <strong>PS grad outside region</strong>.</li>
</ul></li>
<li><strong>Final categories</strong>:
<ul>
<li><strong>PS grad region</strong> → Graduated from a postsecondary institution in Southern MN.</li>
<li><strong>PS grad outside region</strong> → Graduated from a postsecondary institution elsewhere in Minnesota or outside the state.</li>
<li><strong>Did not graduate PS</strong> → Enrolled but did not complete a postsecondary credential.</li>
</ul></li>
<li><strong>Rationale</strong>: This structure highlights the most important distinction for regional employment outcomes: whether graduates complete within Southern MN (anchoring them locally), outside the region (driving mobility), or not at all (linked to disconnection).</li>
</ul>
</section>
<section id="highest-credential-earned-highest.cred.level" class="level4">
<h4 class="anchored" data-anchor-id="highest-credential-earned-highest.cred.level">2. Highest Credential Earned (<code>highest.cred.level</code>)</h4>
<ul>
<li><strong>Original categories</strong>:
<ul>
<li>No college</li>
<li>Some college</li>
<li>Less than associate degree</li>
<li>Associate degree</li>
<li>Bachelor’s degree or higher</li>
</ul></li>
<li><strong>Recoding approach</strong>:
<ul>
<li>Collapsed <em>No college</em> and <em>Some college</em> into <strong>Did not graduate PS</strong>, representing students without a credential.</li>
<li>Collapsed <em>Less than associate degree</em> and <em>Associate degree</em> into <strong>Associate degree or less</strong>, representing sub-baccalaureate completions.</li>
</ul></li>
<li><strong>Final categories</strong>:
<ul>
<li><strong>Did not graduate PS</strong> → No formal credential earned.</li>
<li><strong>Associate degree or less</strong> → Includes certificates, diplomas, and associate degrees.</li>
<li><strong>Bachelor degree or higher</strong> → Represents advanced educational attainment.</li>
</ul></li>
<li><strong>Rationale</strong>: This grouping emphasizes the stepwise distinction between non-completion, sub-baccalaureate pathways (most tied to regional employment), and bachelor’s+ pathways (more strongly tied to statewide or out-of-state mobility).</li>
</ul>
<p><br></p>
</section>
</section>
</section>
<section id="independent-variables" class="level2">
<h2 class="anchored" data-anchor-id="independent-variables">Independent Variables</h2>
<section id="demographics" class="level3">
<h3 class="anchored" data-anchor-id="demographics">1. Demographics</h3>
<ul>
<li><strong>Economic status</strong> → Strong predictor of both PS enrollment/completion and employment outcomes. Low-income students are key to understanding regional pathways.</li>
<li><strong>SpecialEdStatus</strong> → Consistent barrier in both PS and employment; heavily represented in regional pathways.</li>
<li><strong>RaceEthnicity</strong> → Persistent gaps in access, completion, and location of graduation. Helps explain inequities in both mobility and retention.</li>
<li><strong>Gender</strong> → Early postsecondary enrollment and employment differences; useful for modeling even if gaps narrow later.</li>
</ul>
</section>
<section id="high-school-characteristics" class="level3">
<h3 class="anchored" data-anchor-id="high-school-characteristics">2. High School Characteristics</h3>
<ul>
<li><strong>Dem_Desc (Rural vs.&nbsp;Metro)</strong> → Strong link to regional attachment; rural students more likely to stay, metro more mobile/disconnected.</li>
<li><strong>avg.unemp.rate</strong> → Local economic conditions influence both PS location and employment stability.</li>
<li><strong>avg.wage.pct.state</strong> → Higher local wages reduce disconnection and can anchor students regionally.</li>
</ul>
</section>
<section id="high-school-accomplishments" class="level3">
<h3 class="anchored" data-anchor-id="high-school-accomplishments">3. High School Accomplishments</h3>
<ul>
<li><strong>CTE achievement</strong> → Most consistent school-based predictor of regional employment and 2-year PS pathways.</li>
<li><strong>total.cte.courses.taken</strong> → Continuous measure adds granularity beyond concentrator/completer status.</li>
<li><strong>ACTCompositeScore</strong> → Strong signal of academic rigor; predicts 4-year+ pathways and mobility.</li>
<li><strong>MCA Math, Reading, Science</strong> → Reinforce academic readiness dimension; lower scores tied to regional 2-year pathways, higher scores to mobility.</li>
<li><strong>PSEO participation</strong> → Clear driver of 4-year+ completions and out-of-region graduation.</li>
</ul>
</section>
<section id="de-prioritize-drop" class="level3">
<h3 class="anchored" data-anchor-id="de-prioritize-drop">De-prioritize / Drop</h3>
<ul>
<li><strong>English learner / LEP / non-English home</strong> → Weak long-term signals; redundant.</li>
<li><strong>sat.taken</strong> and <strong>took.ACT</strong> → Minimal discriminatory value; not useful for prediction.</li>
<li><strong>ap.exam</strong> → Overlaps with ACT/MCA and PSEO; weaker independent effect.</li>
</ul>
<p><br></p>
</section>
</section>
</section>
<section id="methodology" class="level1">
<h1>Methodology</h1>
<p>This analysis used <strong>classification and regression trees (CART)</strong> to explore the predictive power of demographic, high school context, and accomplishment variables on postsecondary pathways. CART was selected because it:</p>
<ul>
<li>Handles both categorical and continuous predictors without requiring transformation.</li>
<li>Naturally models nonlinear relationships and interactions between variables.</li>
<li>Produces results that are highly interpretable, with decision rules that can be directly linked back to student pathways.</li>
</ul>
<p>For each postsecondary dependent variable, the analysis followed a consistent three-step process:</p>
<ol type="1">
<li><strong>Distribution Analysis</strong>
<ul>
<li>Calculated and visualized the distribution of cases across the recoded categories for each dependent variable.</li>
<li>Established baseline context and highlighted whether any categories were sparsely populated.</li>
</ul></li>
<li><strong>Model Estimation</strong>
<ul>
<li>Estimated three CART models for each dependent variable:
<ul>
<li><strong>Base model</strong>: A fully grown tree without pruning, providing the maximum possible fit and revealing the most detailed set of splits.</li>
<li><strong>Pre-pruned model</strong>: A tree constrained during growth (e.g., limiting maximum depth or minimum split size) to prevent overfitting and to enhance generalizability.</li>
<li><strong>Post-pruned model</strong>: A tree first grown to full size, then pruned back using the complexity parameter (CP) and cross-validation results to balance fit and simplicity.</li>
</ul></li>
</ul></li>
<li><strong>Model Selection</strong>
<ul>
<li>Compared the three models based on cross-validated classification accuracy, error rates, and interpretability.</li>
<li>Final model choice prioritized <strong>predictive strength</strong> while also ensuring <strong>clarity and parsimony</strong>—favoring simpler trees when they performed comparably to more complex ones.</li>
</ul></li>
</ol>
<p>This procedure ensured that the final CART models both maximized predictive accuracy and yielded interpretable insights into how student background and high school experiences influence postsecondary pathways most strongly tied to regional workforce outcomes.</p>
<p><br></p>
</section>
<section id="analysis---post-secondary-location" class="level1">
<h1>Analysis - Post secondary location</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> master <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(economic.status, Gender, RaceEthnicity, SpecialEdStatus, Dem_Desc, avg.unemp.rate, avg.wages.pct.state, ACTCompositeScore, pseo.participant, cte.achievement, total.cte.courses.taken, MCA.M, MCA.R, MCA.S, ps.grad.location.new, highest.cred.level.new)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">names</span>(data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">economic.status</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gender</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RaceEthnicity</td>
</tr>
<tr class="even">
<td style="text-align: left;">SpecialEdStatus</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dem_Desc</td>
</tr>
<tr class="even">
<td style="text-align: left;">avg.unemp.rate</td>
</tr>
<tr class="odd">
<td style="text-align: left;">avg.wages.pct.state</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACTCompositeScore</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pseo.participant</td>
</tr>
<tr class="even">
<td style="text-align: left;">cte.achievement</td>
</tr>
<tr class="odd">
<td style="text-align: left;">total.cte.courses.taken</td>
</tr>
<tr class="even">
<td style="text-align: left;">MCA.M</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MCA.R</td>
</tr>
<tr class="even">
<td style="text-align: left;">MCA.S</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ps.grad.location.new</td>
</tr>
<tr class="even">
<td style="text-align: left;">highest.cred.level.new</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 6%">
<col style="width: 2%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 9%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">economic.status</th>
<th style="text-align: left;">Gender</th>
<th style="text-align: left;">RaceEthnicity</th>
<th style="text-align: right;">SpecialEdStatus</th>
<th style="text-align: left;">Dem_Desc</th>
<th style="text-align: right;">avg.unemp.rate</th>
<th style="text-align: right;">avg.wages.pct.state</th>
<th style="text-align: right;">ACTCompositeScore</th>
<th style="text-align: right;">pseo.participant</th>
<th style="text-align: left;">cte.achievement</th>
<th style="text-align: right;">total.cte.courses.taken</th>
<th style="text-align: right;">MCA.M</th>
<th style="text-align: right;">MCA.R</th>
<th style="text-align: right;">MCA.S</th>
<th style="text-align: left;">ps.grad.location.new</th>
<th style="text-align: left;">highest.cred.level.new</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: left;">M</td>
<td style="text-align: left;">White</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: right;">4.600000</td>
<td style="text-align: right;">0.8566529</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">Did not graduate ps</td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: left;">M</td>
<td style="text-align: left;">White</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Entirely urban</td>
<td style="text-align: right;">2.900000</td>
<td style="text-align: right;">0.9991283</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">No CTE</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">Did not graduate ps</td>
<td style="text-align: left;">Did not graduate ps</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: left;">F</td>
<td style="text-align: left;">White</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: right;">4.666667</td>
<td style="text-align: right;">0.9438229</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">PS grad outside region</td>
<td style="text-align: left;">Bachelor degree or higher</td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: left;">F</td>
<td style="text-align: left;">White</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: right;">4.666667</td>
<td style="text-align: right;">0.8817291</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">PS grad region</td>
<td style="text-align: left;">Associate degree or lower</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: left;">F</td>
<td style="text-align: left;">White</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Urban/town/rural mix</td>
<td style="text-align: right;">6.000000</td>
<td style="text-align: right;">0.8676488</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">No CTE</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">PS grad region</td>
<td style="text-align: left;">Bachelor degree or higher</td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: left;">M</td>
<td style="text-align: left;">White</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Entirely urban</td>
<td style="text-align: right;">5.466667</td>
<td style="text-align: right;">1.0312134</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">CTE Participant</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">PS grad outside region</td>
<td style="text-align: left;">Bachelor degree or higher</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The table below shows that 54% of the individuals did not graduate college, 27% graduated outside their high school region, and only 19% graduated from a college within their region.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>ps.grad.location <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>highest.cred.level.new) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ps.grad.location.new <span class="sc">!=</span> <span class="st">"Attending ps"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ps.grad.location.new =</span> <span class="fu">as.factor</span>(ps.grad.location.new))</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">comma</span>(<span class="fu">nrow</span>(ps.grad.location))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "104,610"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">datatable</span>(<span class="at">data =</span> ps.grad.location <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>            <span class="fu">group_by</span>(ps.grad.location.new) <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>            <span class="fu">mutate</span>(<span class="at">pct =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">%&gt;%</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>            <span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>),</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">class =</span> <span class="st">"cell-border stripe"</span>, </span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">filter =</span> <span class="st">"top"</span>, </span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">rownames =</span> <span class="cn">FALSE</span>,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">options =</span> <span class="fu">list</span>(</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">columnDefs =</span> <span class="fu">list</span>(<span class="fu">list</span>(<span class="at">className =</span> <span class="st">"dt-center"</span>, <span class="at">targets =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)))) <span class="sc">%&gt;%</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">formatCurrency</span>(<span class="dv">2</span>, <span class="st">""</span>, <span class="at">digits =</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">formatPercentage</span>(<span class="dv">3</span>, <span class="at">digits =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-4f3d781fc259555c1dc1" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-4f3d781fc259555c1dc1">{"x":{"filter":"top","vertical":false,"filterHTML":"<tr>\n  <td data-type=\"factor\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"width: 100%; display: none;\">\n      <select multiple=\"multiple\" style=\"width: 100%;\" data-options=\"[&quot;Did not graduate ps&quot;,&quot;PS grad outside region&quot;,&quot;PS grad region&quot;]\"><\/select>\n    <\/div>\n  <\/td>\n  <td data-type=\"integer\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none;position: absolute;width: 200px;opacity: 1\">\n      <div data-min=\"19438\" data-max=\"56651\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"number\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none;position: absolute;width: 200px;opacity: 1\">\n      <div data-min=\"0.185813975719338\" data-max=\"0.541544785393366\" data-scale=\"15\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n<\/tr>","data":[["Did not graduate ps","PS grad outside region","PS grad region"],[56651,28521,19438],[0.5415447853933658,0.2726412388872957,0.1858139757193385]],"container":"<table class=\"cell-border stripe\">\n  <thead>\n    <tr>\n      <th>ps.grad.location.new<\/th>\n      <th>n<\/th>\n      <th>pct<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"targets":2,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatPercentage(data, 1, 3, \",\", \".\", null);\n  }"},{"targets":1,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatCurrency(data, \"\", 0, 3, \",\", \".\", true, null);\n  }"},{"className":"dt-center","targets":[1,2]},{"name":"ps.grad.location.new","targets":0},{"name":"n","targets":1},{"name":"pct","targets":2}],"order":[],"autoWidth":false,"orderClasses":false,"orderCellsTop":true},"selection":{"mode":"multiple","selected":null,"target":"row","selectable":null}},"evals":["options.columnDefs.0.render","options.columnDefs.1.render"],"jsHooks":[]}</script>
</div>
</div>
<p><br></p>
<section id="base-model" class="level2">
<h2 class="anchored" data-anchor-id="base-model">Base Model</h2>
<p>I know the base model is going to overfit and provide an overly complex tree due to having a cost penalty of 0. So I’m just going to print the complexity plot in order to see what the appropriate CP would be to minimize xerror.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>sample_ind <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(ps.grad.location), <span class="fu">nrow</span>(ps.grad.location) <span class="sc">*</span>.<span class="dv">7</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> ps.grad.location[sample_ind,]</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> ps.grad.location[<span class="sc">-</span>sample_ind,]</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Base model</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>ps.grad.location.model <span class="ot">&lt;-</span> <span class="fu">rpart</span>(ps.grad.location.new <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"class"</span>, <span class="at">control =</span> <span class="fu">rpart.control</span>(<span class="at">cp =</span> <span class="dv">0</span>))</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Accuracy</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(ps.grad.location.model, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>accuracy_base <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>ps.grad.location.new)</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="fu">percent</span>(accuracy_base, <span class="at">accuracy =</span> .<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "59.3%"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(ps.grad.location.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = ps.grad.location.new ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0))

Variables actually used in tree construction:
 [1] ACTCompositeScore       avg.unemp.rate          avg.wages.pct.state    
 [4] cte.achievement         Dem_Desc                economic.status        
 [7] Gender                  MCA.M                   MCA.R                  
[10] MCA.S                   pseo.participant        RaceEthnicity          
[13] SpecialEdStatus         total.cte.courses.taken

Root node error: 33548/73227 = 0.45814

n= 73227 

            CP nsplit rel error  xerror      xstd
1   4.2695e-02      0   1.00000 1.00000 0.0040189
2   1.2162e-02      3   0.87191 0.87987 0.0039566
3   8.9722e-03      4   0.85975 0.86574 0.0039460
4   6.1106e-03      5   0.85078 0.85302 0.0039357
5   2.7721e-03      6   0.84467 0.84995 0.0039332
6   1.2445e-03      7   0.84190 0.84372 0.0039279
7   1.0681e-03     11   0.83692 0.83433 0.0039196
8   1.0135e-03     19   0.82375 0.82762 0.0039135
9   7.4520e-04     24   0.81826 0.82148 0.0039078
10  6.5578e-04     26   0.81677 0.82097 0.0039073
11  6.4584e-04     27   0.81611 0.82094 0.0039073
12  6.0610e-04     30   0.81418 0.82056 0.0039070
13  5.9616e-04     33   0.81236 0.82065 0.0039070
14  5.8126e-04     35   0.81117 0.82014 0.0039066
15  5.6635e-04     37   0.81000 0.81957 0.0039060
16  5.0674e-04     38   0.80944 0.81871 0.0039052
17  4.8686e-04     39   0.80893 0.81686 0.0039034
18  4.7693e-04     42   0.80747 0.81686 0.0039034
19  4.4712e-04     43   0.80699 0.81576 0.0039024
20  3.3782e-04     44   0.80655 0.81540 0.0039020
21  3.2789e-04     48   0.80512 0.81540 0.0039020
22  2.9808e-04     52   0.80357 0.81507 0.0039017
23  2.8318e-04     57   0.80207 0.81570 0.0039023
24  2.6827e-04     59   0.80151 0.81465 0.0039013
25  2.4592e-04     63   0.80044 0.81319 0.0038999
26  2.3846e-04     68   0.79912 0.81278 0.0038995
27  2.2356e-04     77   0.79665 0.81248 0.0038992
28  2.0866e-04     79   0.79620 0.81239 0.0038991
29  1.9872e-04     87   0.79438 0.81179 0.0038985
30  1.8630e-04     90   0.79379 0.81188 0.0038986
31  1.7885e-04    102   0.79131 0.81173 0.0038985
32  1.6891e-04    110   0.78988 0.81301 0.0038997
33  1.6394e-04    113   0.78938 0.81289 0.0038996
34  1.6096e-04    117   0.78872 0.81379 0.0039005
35  1.5898e-04    123   0.78774 0.81355 0.0039002
36  1.4904e-04    135   0.78535 0.81352 0.0039002
37  1.4308e-04    152   0.78279 0.81424 0.0039009
38  1.4159e-04    158   0.78192 0.81528 0.0039019
39  1.3910e-04    166   0.78079 0.81525 0.0039019
40  1.3712e-04    177   0.77859 0.81507 0.0039017
41  1.3414e-04    182   0.77790 0.81510 0.0039017
42  1.2917e-04    202   0.77474 0.81713 0.0039037
43  1.2668e-04    210   0.77364 0.81713 0.0039037
44  1.1923e-04    214   0.77313 0.81763 0.0039042
45  1.1327e-04    255   0.76803 0.81853 0.0039050
46  1.1178e-04    262   0.76711 0.81933 0.0039058
47  1.0930e-04    275   0.76556 0.81933 0.0039058
48  1.0859e-04    282   0.76475 0.81954 0.0039060
49  1.0731e-04    307   0.76177 0.81990 0.0039063
50  1.0433e-04    312   0.76124 0.82056 0.0039070
51  1.0318e-04    344   0.75772 0.82094 0.0039073
52  1.0135e-04    375   0.75411 0.82133 0.0039077
53  9.9360e-05    386   0.75295 0.82133 0.0039077
54  9.6876e-05    402   0.75128 0.82261 0.0039089
55  9.4392e-05    408   0.75069 0.82297 0.0039092
56  9.3682e-05    421   0.74911 0.82327 0.0039095
57  9.2736e-05    429   0.74833 0.82348 0.0039097
58  8.9424e-05    446   0.74630 0.82467 0.0039108
59  8.4456e-05    522   0.73945 0.82610 0.0039121
60  8.3463e-05    541   0.73742 0.82625 0.0039123
61  7.9488e-05    546   0.73700 0.82777 0.0039137
62  7.7501e-05    579   0.73364 0.82851 0.0039144
63  7.4520e-05    586   0.73304 0.82959 0.0039154
64  7.1539e-05    705   0.72308 0.83084 0.0039165
65  6.9552e-05    738   0.72034 0.83111 0.0039167
66  6.8133e-05    786   0.71688 0.83117 0.0039168
67  6.7068e-05    793   0.71641 0.83117 0.0039168
68  6.4584e-05    823   0.71426 0.83558 0.0039208
69  6.2928e-05    861   0.71074 0.83558 0.0039208
70  5.9616e-05    870   0.71018 0.83582 0.0039210
71  5.7132e-05   1200   0.68866 0.83749 0.0039225
72  5.5358e-05   1215   0.68776 0.83939 0.0039241
73  5.4648e-05   1235   0.68639 0.84240 0.0039268
74  5.4196e-05   1247   0.68564 0.84240 0.0039268
75  5.3654e-05   1258   0.68505 0.84240 0.0039268
76  5.2164e-05   1293   0.68272 0.84309 0.0039273
77  5.1099e-05   1325   0.68040 0.84324 0.0039275
78  4.9680e-05   1345   0.67927 0.84330 0.0039275
79  4.7693e-05   1425   0.67470 0.84902 0.0039324
80  4.7196e-05   1444   0.67372 0.84932 0.0039327
81  4.6841e-05   1465   0.67229 0.84983 0.0039331
82  4.4712e-05   1474   0.67184 0.85084 0.0039339
83  4.1731e-05   1643   0.66320 0.85445 0.0039369
84  3.9744e-05   1660   0.66245 0.85791 0.0039397
85  3.8325e-05   1733   0.65888 0.85811 0.0039399
86  3.7260e-05   1746   0.65828 0.85946 0.0039410
87  3.5770e-05   1811   0.65557 0.85981 0.0039413
88  3.4776e-05   1854   0.65393 0.86014 0.0039415
89  3.4066e-05   1860   0.65372 0.86014 0.0039415
90  2.9808e-05   1867   0.65348 0.87594 0.0039537
91  2.7515e-05   2262   0.64114 0.87636 0.0039541
92  2.6827e-05   2279   0.64054 0.87886 0.0039559
93  2.6496e-05   2304   0.63980 0.87892 0.0039559
94  2.5550e-05   2334   0.63894 0.88110 0.0039575
95  2.4840e-05   2343   0.63870 0.88136 0.0039577
96  2.4388e-05   2349   0.63855 0.88342 0.0039592
97  2.3846e-05   2360   0.63828 0.88342 0.0039592
98  2.2356e-05   2405   0.63712 0.88411 0.0039597
99  2.1291e-05   2453   0.63601 0.88709 0.0039618
100 2.0636e-05   2467   0.63572 0.88709 0.0039618
101 1.9872e-05   2480   0.63545 0.88742 0.0039620
102 1.7885e-05   2567   0.63363 0.88929 0.0039634
103 1.7388e-05   2600   0.63300 0.88926 0.0039633
104 1.6560e-05   2616   0.63271 0.88926 0.0039633
105 1.4904e-05   2633   0.63238 0.89803 0.0039693
106 1.2775e-05   2819   0.62937 0.89844 0.0039696
107 1.1923e-05   2826   0.62928 0.90005 0.0039706
108 1.1178e-05   2851   0.62898 0.90014 0.0039707
109 9.9360e-06   2859   0.62889 0.90399 0.0039732
110 8.5166e-06   2929   0.62817 0.90464 0.0039736
111 7.4520e-06   2936   0.62811 0.90640 0.0039748
112 5.9616e-06   2964   0.62791 0.90649 0.0039748
113 4.9680e-06   2994   0.62773 0.90852 0.0039761
114 4.2583e-06   3006   0.62767 0.90876 0.0039762
115 3.7260e-06   3020   0.62761 0.90873 0.0039762
116 0.0000e+00   3028   0.62758 0.90882 0.0039763</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(ps.grad.location.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_post_secondary_paths_CART_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Key takeaways from base tree results</strong></p>
<ul>
<li><strong>Accuracy</strong>: 59.3%</li>
<li><strong>Variables used:</strong> 14/14
<ul>
<li>Demographics: 4/4</li>
<li>HS Characteristics: 3/3</li>
<li>HS Accomplishments: 7/7</li>
</ul></li>
<li><strong>Lowest cross-validation error:</strong>
<ul>
<li>Step: 31</li>
<li>xerror: 0.81173</li>
<li>cp: 1.7885e-04</li>
<li>split: 102</li>
</ul></li>
<li>Total splits: 3,028</li>
</ul>
<p><br></p>
</section>
<section id="pre-pruning" class="level2">
<h2 class="anchored" data-anchor-id="pre-pruning">Pre-pruning</h2>
<p>Next, we need to prune. We can either pre-prune or post-prune. We will start with pre-pruning and use each method - max depth, min depth, and min bucket. It’s recommended that I start with the following parameters;</p>
<ul>
<li>maxdepth: 5</li>
<li>minsplit: round(2% of nrow(train)).</li>
<li>minbucket: round(minsplit / 3).</li>
<li>cp = 0</li>
</ul>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>maxdepth <span class="ot">=</span> <span class="dv">5</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>minsplit <span class="ot">=</span> <span class="fu">round</span>(.<span class="dv">02</span><span class="sc">*</span><span class="fu">nrow</span>(train))</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>minbucket <span class="ot">=</span> <span class="fu">round</span>(minsplit <span class="sc">/</span> <span class="dv">3</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>ps.grad.location.model.preprune <span class="ot">&lt;-</span> <span class="fu">rpart</span>(ps.grad.location.new <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"class"</span>, </span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">control =</span> <span class="fu">rpart.control</span>(<span class="at">cp =</span> <span class="dv">0</span>, <span class="at">maxdepth =</span> maxdepth, <span class="at">minsplit =</span> minsplit, <span class="at">minbucket =</span> minbucket))</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Accuracy</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(ps.grad.location.model.preprune, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>accuracy_preprun <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>ps.grad.location.new)</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a><span class="fu">percent</span>(accuracy_preprun, <span class="at">accuracy =</span> .<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "61.7%"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(ps.grad.location.model.preprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = ps.grad.location.new ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0, maxdepth = maxdepth, minsplit = minsplit, 
        minbucket = minbucket))

Variables actually used in tree construction:
[1] ACTCompositeScore economic.status   MCA.R             pseo.participant 
[5] RaceEthnicity    

Root node error: 33548/73227 = 0.45814

n= 73227 

         CP nsplit rel error  xerror      xstd
1 0.0426950      0   1.00000 1.00000 0.0040189
2 0.0121617      3   0.87191 0.88303 0.0039589
3 0.0089722      4   0.85975 0.86303 0.0039438
4 0.0061106      5   0.85078 0.85674 0.0039388
5 0.0027721      6   0.84467 0.85281 0.0039356
6 0.0000000      7   0.84190 0.84741 0.0039310</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(ps.grad.location.model.preprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_post_secondary_paths_CART_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Key takeaways from base tree results</strong></p>
<ul>
<li><strong>Accuracy</strong>: 59.3% –&gt; 61.7%</li>
<li><strong>Variables used:</strong> 5/14
<ul>
<li>Demographics: 2/4 - Race, economic status</li>
<li>HS Characteristics: 0/3</li>
<li>HS Accomplishments: 3/7 - ACT, MCA, PSEO</li>
</ul></li>
<li><strong>Lowest cross-validation error:</strong>
<ul>
<li>Step: 6</li>
<li>xerror: 0.84741</li>
<li>cp: 0</li>
<li>split: 7</li>
</ul></li>
<li>Total splits: 7</li>
</ul>
<p><br></p>
</section>
<section id="post-pruning" class="level2">
<h2 class="anchored" data-anchor-id="post-pruning">Post-pruning</h2>
<p>The idea here is to allow the decision tree to grow fully and observe the CP value. There are two methods for identifying the CP code;</p>
<ol type="1">
<li>Use the cp value with the lowest xerror from the base model.</li>
<li>Use the cp value with the next lowest xerror that is within the standard error.</li>
</ol>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>cp_table <span class="ot">&lt;-</span> ps.grad.location.model.preprune<span class="sc">$</span>cptable</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>min_xerror <span class="ot">&lt;-</span> <span class="fu">min</span>(cp_table[, <span class="st">"xerror"</span>])</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>min_xerror_se <span class="ot">&lt;-</span> cp_table[<span class="fu">which.min</span>(cp_table[,<span class="st">"xerror"</span>]), <span class="st">"xstd"</span>]</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>threshold <span class="ot">&lt;-</span> min_xerror <span class="sc">+</span> min_xerror_se</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>one_se_index <span class="ot">&lt;-</span> <span class="fu">which</span>(cp_table[, <span class="st">"xerror"</span>] <span class="sc">&lt;=</span> threshold)[<span class="dv">1</span>] </span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>cp_1se <span class="ot">&lt;-</span> cp_table[one_se_index, <span class="st">"CP"</span>]</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>optimal_cp <span class="ot">&lt;-</span> ps.grad.location.model.preprune<span class="sc">$</span>cptable[<span class="fu">which.min</span>(ps.grad.location.model.preprune<span class="sc">$</span>cptable[, <span class="st">"xerror"</span>]), <span class="st">"CP"</span>]</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Prune the hr_base_model based on the optimal cp value</span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>ps.grad.location.model.postprune <span class="ot">&lt;-</span> rpart<span class="sc">::</span><span class="fu">prune</span>(ps.grad.location.model.preprune, <span class="at">cp =</span> cp_1se)</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the accuracy of the pruned tree</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(ps.grad.location.model.postprune, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>accuracy_postprun <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>ps.grad.location.new)</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a><span class="fu">percent</span>(accuracy_postprun, <span class="at">accuracy =</span> .<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "61.7%"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(ps.grad.location.model.postprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = ps.grad.location.new ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0, maxdepth = maxdepth, minsplit = minsplit, 
        minbucket = minbucket))

Variables actually used in tree construction:
[1] ACTCompositeScore economic.status   MCA.R             pseo.participant 
[5] RaceEthnicity    

Root node error: 33548/73227 = 0.45814

n= 73227 

         CP nsplit rel error  xerror      xstd
1 0.0426950      0   1.00000 1.00000 0.0040189
2 0.0121617      3   0.87191 0.88303 0.0039589
3 0.0089722      4   0.85975 0.86303 0.0039438
4 0.0061106      5   0.85078 0.85674 0.0039388
5 0.0027721      6   0.84467 0.85281 0.0039356
6 0.0000000      7   0.84190 0.84741 0.0039310</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(ps.grad.location.model.postprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_post_secondary_paths_CART_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Key takeaways from base tree results</strong></p>
<ul>
<li><strong>Accuracy</strong>: 61.7% –&gt; 61.7%</li>
<li><strong>Variables used:</strong> 5/14
<ul>
<li>Demographics: 2/4 - Race, economic status</li>
<li>HS Characteristics: 0/3</li>
<li>HS Accomplishments: 3/7 - ACT, MCA, PSEO</li>
</ul></li>
<li><strong>Lowest cross-validation error:</strong>
<ul>
<li>Step: 6</li>
<li>xerror: 0.84741</li>
<li>cp: 0</li>
<li>split: 7</li>
</ul></li>
<li>Total splits: 7</li>
</ul>
<p>So, the accuracy of these are;</p>
<ul>
<li>Base model: 59.3%</li>
<li>Pre-pruned model: 61.7%</li>
<li>Post-pruned model: 61.7%</li>
</ul>
<p>The post-pruned model is the same as athe pre-pruned’s. I will use the pre-pruned model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot tree</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(ps.grad.location.model.preprune, <span class="at">nn =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_post_secondary_paths_CART_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="main-takeaway" class="level2">
<h2 class="anchored" data-anchor-id="main-takeaway"><strong>Main Takeaway</strong></h2>
<p><strong>Model Performance</strong><br>
The pre-pruned tree achieved <strong>61.7% accuracy</strong> with a root node error of <strong>45.8%</strong>. This represents a meaningful improvement over the baseline distribution (where 54.2% of students did not graduate PS) and shows that a relatively small set of predictors can explain important variation in postsecondary graduation location.</p>
<p><strong>Key Predictors</strong><br>
The most influential predictors retained after pruning were:</p>
<ul>
<li><strong>MCA Reading (MCA.R)</strong></li>
<li><strong>ACT Composite Score</strong></li>
<li><strong>Economic Status</strong></li>
<li><strong>PSEO Participation</strong></li>
<li><strong>Race/Ethnicity</strong></li>
</ul>
<p><strong>Interpretation of Tree Structure</strong><br>
Regional postsecondary graduation was most strongly tied to <strong>moderate academic readiness</strong> combined with <strong>economic disadvantage</strong>. Students with <strong>mid-range ACT scores (≥24)</strong> and <strong>low-income backgrounds</strong> were more likely to complete in the region rather than outside of it. This highlights how regional institutions serve as a key pathway for disadvantaged but academically prepared students.</p>
<p>Conversely, students with <strong>low MCA Reading scores (&lt;4)</strong> or <strong>low ACT scores (&lt;24)</strong> were far more likely to not graduate at all, underscoring the role of academic preparation in determining access to completion. Among students with stronger academic scores, <strong>PSEO participation</strong> and <strong>advantaged economic status</strong> pushed them toward completion outside the region, reflecting the mobility pipeline.</p>
<p><strong>Summary</strong><br>
The CART model indicates that <strong>regional completions cluster among students who combine modest academic readiness with economic disadvantage</strong>, whereas <strong>high scorers and PSEO participants</strong> overwhelmingly complete outside the region. The strongest barrier remains <strong>low academic readiness</strong>, which is heavily associated with not graduating from postsecondary at all.</p>
<p><strong>Policy Implications</strong><br>
These findings reinforce that <strong>Southern MN’s workforce stability depends on regional postsecondary institutions’ ability to serve low-income students with mid-level academic preparation</strong>. Strengthening supports for these students — such as developmental coursework, wraparound advising, and affordability measures — can improve completion rates and sustain the regional workforce. At the same time, retaining high-achieving students will require <strong>new strategies to connect PSEO participants and bachelor’s-bound students back to local opportunities</strong>, since they are most likely to complete outside the region and enter mobility pathways.</p>
<p><br></p>
</section>
</section>
<section id="analysis---highest-credential-earned" class="level1">
<h1>Analysis - Highest Credential Earned</h1>
<p>The table below shows that 54% of the individuals did not graduate college, 31% graduated with a Bachelor degree or higher, and 15% graduated with an Associate degree or lower.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>highest.cred.level <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>ps.grad.location.new) <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(highest.cred.level.new <span class="sc">!=</span> <span class="st">"Attending ps"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">highest.cred.level.new =</span> <span class="fu">as.factor</span>(highest.cred.level.new))</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="fu">comma</span>(<span class="fu">nrow</span>(highest.cred.level))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "104,613"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">datatable</span>(<span class="at">data =</span> highest.cred.level <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>            <span class="fu">group_by</span>(highest.cred.level.new) <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>            <span class="fu">mutate</span>(<span class="at">pct =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">%&gt;%</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>            <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>            <span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>),</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">class =</span> <span class="st">"cell-border stripe"</span>, </span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">filter =</span> <span class="st">"top"</span>, </span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">rownames =</span> <span class="cn">FALSE</span>,</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">options =</span> <span class="fu">list</span>(</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">columnDefs =</span> <span class="fu">list</span>(<span class="fu">list</span>(<span class="at">className =</span> <span class="st">"dt-center"</span>, <span class="at">targets =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)))) <span class="sc">%&gt;%</span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">formatCurrency</span>(<span class="dv">2</span>, <span class="st">""</span>, <span class="at">digits =</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">formatPercentage</span>(<span class="dv">3</span>, <span class="at">digits =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-10e190d090a63b555110" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-10e190d090a63b555110">{"x":{"filter":"top","vertical":false,"filterHTML":"<tr>\n  <td data-type=\"factor\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"width: 100%; display: none;\">\n      <select multiple=\"multiple\" style=\"width: 100%;\" data-options=\"[&quot;Associate degree or lower&quot;,&quot;Bachelor degree or higher&quot;,&quot;Did not graduate ps&quot;]\"><\/select>\n    <\/div>\n  <\/td>\n  <td data-type=\"integer\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none;position: absolute;width: 200px;opacity: 1\">\n      <div data-min=\"15169\" data-max=\"56651\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"number\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n    <div style=\"display: none;position: absolute;width: 200px;opacity: 1\">\n      <div data-min=\"0.145001099289763\" data-max=\"0.541529255446264\" data-scale=\"15\"><\/div>\n      <span style=\"float: left;\"><\/span>\n      <span style=\"float: right;\"><\/span>\n    <\/div>\n  <\/td>\n<\/tr>","data":[["Associate degree or lower","Bachelor degree or higher","Did not graduate ps"],[15169,32793,56651],[0.1450010992897632,0.3134696452639729,0.5415292554462638]],"container":"<table class=\"cell-border stripe\">\n  <thead>\n    <tr>\n      <th>highest.cred.level.new<\/th>\n      <th>n<\/th>\n      <th>pct<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"targets":2,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatPercentage(data, 1, 3, \",\", \".\", null);\n  }"},{"targets":1,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatCurrency(data, \"\", 0, 3, \",\", \".\", true, null);\n  }"},{"className":"dt-center","targets":[1,2]},{"name":"highest.cred.level.new","targets":0},{"name":"n","targets":1},{"name":"pct","targets":2}],"order":[],"autoWidth":false,"orderClasses":false,"orderCellsTop":true},"selection":{"mode":"multiple","selected":null,"target":"row","selectable":null}},"evals":["options.columnDefs.0.render","options.columnDefs.1.render"],"jsHooks":[]}</script>
</div>
</div>
<p><br></p>
<section id="base-model-1" class="level2">
<h2 class="anchored" data-anchor-id="base-model-1">Base Model</h2>
<p>I know the base model is going to overfit and provide an overly complex tree due to having a cost penalty of 0. So I’m just going to print the complexity plot in order to see what the appropriate CP would be to minimize xerror.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>sample_ind <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(highest.cred.level), <span class="fu">nrow</span>(highest.cred.level) <span class="sc">*</span>.<span class="dv">7</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> highest.cred.level[sample_ind,]</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> highest.cred.level[<span class="sc">-</span>sample_ind,]</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Base model</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>highest.cred.level.model <span class="ot">&lt;-</span> <span class="fu">rpart</span>(highest.cred.level.new <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"class"</span>, <span class="at">control =</span> <span class="fu">rpart.control</span>(<span class="at">cp =</span> <span class="dv">0</span>))</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Accuracy</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(highest.cred.level.model, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>accuracy_base <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>highest.cred.level.new)</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a><span class="fu">percent</span>(accuracy_base, <span class="at">accuracy =</span> .<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "63.3%"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(highest.cred.level.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = highest.cred.level.new ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0))

Variables actually used in tree construction:
 [1] ACTCompositeScore       avg.unemp.rate          avg.wages.pct.state    
 [4] cte.achievement         Dem_Desc                economic.status        
 [7] Gender                  MCA.M                   MCA.R                  
[10] MCA.S                   pseo.participant        RaceEthnicity          
[13] SpecialEdStatus         total.cte.courses.taken

Root node error: 33600/73229 = 0.45883

n= 73229 

            CP nsplit rel error  xerror      xstd
1   7.4375e-02      0   1.00000 1.00000 0.0040132
2   3.1280e-02      2   0.85125 0.85351 0.0039312
3   2.5089e-02      3   0.81997 0.82199 0.0039035
4   5.8036e-03      4   0.79488 0.79360 0.0038754
5   3.6310e-03      7   0.77705 0.77637 0.0038568
6   2.5357e-03      8   0.77342 0.76899 0.0038485
7   2.4901e-03     16   0.74786 0.75479 0.0038320
8   1.1310e-03     19   0.74039 0.74033 0.0038143
9   1.0714e-03     21   0.73813 0.73765 0.0038110
10  9.9702e-04     22   0.73705 0.73768 0.0038110
11  8.7798e-04     24   0.73506 0.73673 0.0038098
12  8.3333e-04     26   0.73330 0.73583 0.0038087
13  8.0357e-04     27   0.73247 0.73455 0.0038070
14  7.0685e-04     29   0.73086 0.73390 0.0038062
15  6.1012e-04     33   0.72804 0.73179 0.0038035
16  6.0516e-04     35   0.72682 0.73140 0.0038030
17  5.9524e-04     38   0.72500 0.73119 0.0038027
18  3.7202e-04     39   0.72440 0.72780 0.0037983
19  3.5714e-04     45   0.72217 0.72768 0.0037982
20  3.2738e-04     51   0.72003 0.72786 0.0037984
21  3.0952e-04     56   0.71839 0.72729 0.0037977
22  2.9762e-04     62   0.71652 0.72661 0.0037968
23  2.8770e-04     65   0.71562 0.72658 0.0037967
24  2.7778e-04     69   0.71446 0.72631 0.0037964
25  2.6786e-04     73   0.71330 0.72598 0.0037960
26  2.5794e-04     75   0.71277 0.72551 0.0037953
27  2.5298e-04     79   0.71170 0.72536 0.0037951
28  2.4802e-04     81   0.71119 0.72536 0.0037951
29  2.3810e-04     84   0.71045 0.72551 0.0037953
30  2.3065e-04     85   0.71021 0.72515 0.0037949
31  2.2321e-04     89   0.70929 0.72372 0.0037930
32  2.1825e-04     93   0.70839 0.72360 0.0037928
33  2.0833e-04     96   0.70774 0.72366 0.0037929
34  1.9345e-04    101   0.70670 0.72339 0.0037926
35  1.7857e-04    116   0.70321 0.72360 0.0037928
36  1.7113e-04    127   0.70092 0.72247 0.0037913
37  1.6369e-04    133   0.69988 0.72253 0.0037914
38  1.5625e-04    139   0.69890 0.72262 0.0037915
39  1.4881e-04    143   0.69827 0.72274 0.0037917
40  1.3889e-04    157   0.69580 0.72259 0.0037915
41  1.3690e-04    166   0.69411 0.72304 0.0037921
42  1.3393e-04    171   0.69342 0.72304 0.0037921
43  1.3095e-04    184   0.69155 0.72304 0.0037921
44  1.2897e-04    189   0.69089 0.72277 0.0037917
45  1.1905e-04    195   0.69012 0.72280 0.0037918
46  1.0913e-04    235   0.68521 0.72384 0.0037931
47  1.0417e-04    238   0.68488 0.72455 0.0037941
48  1.0119e-04    282   0.67967 0.72497 0.0037946
49  9.9206e-05    289   0.67896 0.72497 0.0037946
50  9.6726e-05    305   0.67717 0.72649 0.0037966
51  8.9286e-05    311   0.67646 0.72667 0.0037969
52  8.1845e-05    407   0.66732 0.72937 0.0038004
53  8.0782e-05    422   0.66595 0.73220 0.0038040
54  7.9365e-05    429   0.66539 0.73217 0.0038040
55  7.4405e-05    459   0.66298 0.73479 0.0038073
56  7.2279e-05    494   0.66027 0.73565 0.0038084
57  7.1429e-05    524   0.65777 0.73574 0.0038085
58  7.0685e-05    529   0.65741 0.73586 0.0038087
59  6.9444e-05    541   0.65646 0.73634 0.0038093
60  6.8027e-05    564   0.65476 0.73634 0.0038093
61  6.6964e-05    579   0.65348 0.73682 0.0038099
62  6.2500e-05    636   0.64902 0.74408 0.0038190
63  6.2229e-05    652   0.64786 0.74461 0.0038196
64  5.9524e-05    722   0.64134 0.74539 0.0038206
65  5.3571e-05    968   0.62545 0.74914 0.0038252
66  5.2083e-05    987   0.62438 0.75381 0.0038308
67  5.1020e-05    999   0.62375 0.75417 0.0038312
68  4.9603e-05   1020   0.62250 0.75417 0.0038312
69  4.8363e-05   1066   0.62000 0.75759 0.0038353
70  4.7619e-05   1078   0.61940 0.75771 0.0038355
71  4.6296e-05   1092   0.61854 0.75798 0.0038358
72  4.4643e-05   1102   0.61804 0.75932 0.0038374
73  4.2989e-05   1333   0.60631 0.76214 0.0038407
74  4.1667e-05   1345   0.60574 0.76283 0.0038415
75  3.9683e-05   1406   0.60247 0.76565 0.0038447
76  3.7202e-05   1516   0.59729 0.76750 0.0038468
77  3.5714e-05   1561   0.59518 0.76872 0.0038482
78  3.4722e-05   1592   0.59384 0.76902 0.0038486
79  2.9762e-05   1598   0.59363 0.78321 0.0038643
80  2.6786e-05   2012   0.58062 0.78408 0.0038653
81  2.6455e-05   2039   0.57985 0.78503 0.0038663
82  2.4802e-05   2050   0.57955 0.78640 0.0038678
83  2.3810e-05   2074   0.57890 0.78926 0.0038708
84  2.2321e-05   2104   0.57815 0.79048 0.0038721
85  2.1259e-05   2186   0.57601 0.79583 0.0038777
86  2.0833e-05   2197   0.57574 0.79583 0.0038777
87  1.9841e-05   2211   0.57542 0.79601 0.0038779
88  1.8601e-05   2280   0.57387 0.79798 0.0038799
89  1.7857e-05   2288   0.57372 0.79845 0.0038804
90  1.7007e-05   2330   0.57283 0.79848 0.0038804
91  1.4881e-05   2344   0.57259 0.80598 0.0038880
92  1.1905e-05   2533   0.56949 0.80693 0.0038890
93  9.9206e-06   2592   0.56869 0.81247 0.0038944
94  8.5034e-06   2679   0.56777 0.81333 0.0038952
95  7.4405e-06   2693   0.56765 0.81536 0.0038972
96  5.9524e-06   2725   0.56741 0.81560 0.0038974
97  4.9603e-06   2745   0.56726 0.81765 0.0038994
98  4.2517e-06   2794   0.56699 0.81804 0.0038998
99  3.7202e-06   2801   0.56696 0.81821 0.0038999
100 2.9762e-06   2809   0.56693 0.81824 0.0039000
101 0.0000e+00   2819   0.56690 0.81833 0.0039000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(highest.cred.level.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_post_secondary_paths_CART_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Key takeaways from base tree results</strong></p>
<ul>
<li><strong>Accuracy</strong>: 63.3%</li>
<li><strong>Variables used:</strong> 14/14
<ul>
<li>Demographics: 4/4</li>
<li>HS Characteristics: 3/3</li>
<li>HS Accomplishments: 7/7</li>
</ul></li>
<li><strong>Lowest cross-validation error:</strong>
<ul>
<li>Step: 36</li>
<li>xerror: 0.72247</li>
<li>cp: 1.7113e-04</li>
<li>Splits: 127</li>
</ul></li>
<li>Total splits: 2,819</li>
</ul>
<p><br></p>
</section>
<section id="pre-pruning-1" class="level2">
<h2 class="anchored" data-anchor-id="pre-pruning-1">Pre-pruning</h2>
<p>Next, we need to prune. We can either pre-prune or post-prune. We will start with pre-pruning and use each method - max depth, min depth, and min bucket. It’s recommended that I start with the following parameters;</p>
<ul>
<li>maxdepth: 5</li>
<li>minsplit: round(2% of nrow(train)).</li>
<li>minbucket: round(minsplit / 3).</li>
<li>cp = 0</li>
</ul>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>maxdepth <span class="ot">=</span> <span class="dv">5</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>minsplit <span class="ot">=</span> <span class="fu">round</span>(.<span class="dv">02</span><span class="sc">*</span><span class="fu">nrow</span>(train))</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>minbucket <span class="ot">=</span> <span class="fu">round</span>(minsplit <span class="sc">/</span> <span class="dv">3</span>)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>highest.cred.level.model.preprune <span class="ot">&lt;-</span> <span class="fu">rpart</span>(highest.cred.level.new <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"class"</span>, </span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">control =</span> <span class="fu">rpart.control</span>(<span class="at">cp =</span> <span class="dv">0</span>, <span class="at">maxdepth =</span> maxdepth, <span class="at">minsplit =</span> minsplit, <span class="at">minbucket =</span> minbucket))</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Accuracy</span></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(highest.cred.level.model.preprune, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>accuracy_preprun <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>highest.cred.level.new)</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a><span class="fu">percent</span>(accuracy_preprun, <span class="at">accuracy =</span> .<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "64.2%"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(highest.cred.level.model.preprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = highest.cred.level.new ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0, maxdepth = maxdepth, minsplit = minsplit, 
        minbucket = minbucket))

Variables actually used in tree construction:
[1] ACTCompositeScore       economic.status         MCA.R                  
[4] pseo.participant        RaceEthnicity           total.cte.courses.taken

Root node error: 33600/73229 = 0.45883

n= 73229 

         CP nsplit rel error  xerror      xstd
1 0.0743750      0   1.00000 1.00000 0.0040132
2 0.0312798      2   0.85125 0.85125 0.0039293
3 0.0250893      3   0.81997 0.81872 0.0039004
4 0.0058036      4   0.79488 0.79426 0.0038761
5 0.0036310      6   0.78327 0.78690 0.0038683
6 0.0000000      7   0.77964 0.78149 0.0038625</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(highest.cred.level.model.preprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_post_secondary_paths_CART_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Key takeaways from base tree results</strong></p>
<ul>
<li><strong>Accuracy</strong>: 63.3% –&gt; 64.2%</li>
<li><strong>Variables used:</strong> 6/14
<ul>
<li>Demographics: 2/4 - Race and economic status</li>
<li>HS Characteristics: 0/3</li>
<li>HS Accomplishments: 4/7 - ACT, MCA, PSEO, CTE</li>
</ul></li>
<li><strong>Lowest cross-validation error:</strong>
<ul>
<li>Step: 6</li>
<li>xerror: 0.78149</li>
<li>cp: 0</li>
<li>Splits: 7</li>
</ul></li>
<li>Total splits: 7</li>
</ul>
<p><br></p>
</section>
<section id="post-pruning-1" class="level2">
<h2 class="anchored" data-anchor-id="post-pruning-1">Post-pruning</h2>
<p>The idea here is to allow the decision tree to grow fully and observe the CP value. There are two methods for identifying the CP code;</p>
<ol type="1">
<li>Use the cp value with the lowest xerror from the base model.</li>
<li>Use the cp value with the next lowest xerror that is within the standard error.</li>
</ol>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>cp_table <span class="ot">&lt;-</span> highest.cred.level.model.preprune<span class="sc">$</span>cptable</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>min_xerror <span class="ot">&lt;-</span> <span class="fu">min</span>(cp_table[, <span class="st">"xerror"</span>])</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>min_xerror_se <span class="ot">&lt;-</span> cp_table[<span class="fu">which.min</span>(cp_table[,<span class="st">"xerror"</span>]), <span class="st">"xstd"</span>]</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>threshold <span class="ot">&lt;-</span> min_xerror <span class="sc">+</span> min_xerror_se</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>one_se_index <span class="ot">&lt;-</span> <span class="fu">which</span>(cp_table[, <span class="st">"xerror"</span>] <span class="sc">&lt;=</span> threshold)[<span class="dv">1</span>] </span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>cp_1se <span class="ot">&lt;-</span> cp_table[one_se_index, <span class="st">"CP"</span>]</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>optimal_cp <span class="ot">&lt;-</span> highest.cred.level.model.preprune<span class="sc">$</span>cptable[<span class="fu">which.min</span>(highest.cred.level.model.preprune<span class="sc">$</span>cptable[, <span class="st">"xerror"</span>]), <span class="st">"CP"</span>]</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Prune the hr_base_model based on the optimal cp value</span></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>highest.cred.level.model.postprune <span class="ot">&lt;-</span> rpart<span class="sc">::</span><span class="fu">prune</span>(highest.cred.level.model.preprune, <span class="at">cp =</span> cp_1se)</span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the accuracy of the pruned tree</span></span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(highest.cred.level.model.postprune, test, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a>accuracy_postprun <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred <span class="sc">==</span> test<span class="sc">$</span>highest.cred.level.new)</span>
<span id="cb39-23"><a href="#cb39-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-24"><a href="#cb39-24" aria-hidden="true" tabindex="-1"></a><span class="fu">percent</span>(accuracy_postprun, <span class="at">accuracy =</span> .<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "64.2%"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the complexity plot</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(highest.cred.level.model.postprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = highest.cred.level.new ~ ., data = train, method = "class", 
    control = rpart.control(cp = 0, maxdepth = maxdepth, minsplit = minsplit, 
        minbucket = minbucket))

Variables actually used in tree construction:
[1] ACTCompositeScore       economic.status         MCA.R                  
[4] pseo.participant        RaceEthnicity           total.cte.courses.taken

Root node error: 33600/73229 = 0.45883

n= 73229 

         CP nsplit rel error  xerror      xstd
1 0.0743750      0   1.00000 1.00000 0.0040132
2 0.0312798      2   0.85125 0.85125 0.0039293
3 0.0250893      3   0.81997 0.81872 0.0039004
4 0.0058036      4   0.79488 0.79426 0.0038761
5 0.0036310      6   0.78327 0.78690 0.0038683
6 0.0000000      7   0.77964 0.78149 0.0038625</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(highest.cred.level.model.postprune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_post_secondary_paths_CART_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Key takeaways from base tree results</strong></p>
<ul>
<li><strong>Accuracy</strong>: 64.2% –&gt; 64.2%</li>
<li><strong>Variables used:</strong> 6/14
<ul>
<li>Demographics: 2/4 - Race and economic status</li>
<li>HS Characteristics: 0/3</li>
<li>HS Accomplishments: 4/7 - ACT, MCA, PSEO, CTE</li>
</ul></li>
<li><strong>Lowest cross-validation error:</strong>
<ul>
<li>Step: 6</li>
<li>xerror: 0.78149</li>
<li>cp: 0</li>
<li>Splits: 7</li>
</ul></li>
<li>Total splits: 7</li>
</ul>
<p>So, the accuracy of these are;</p>
<ul>
<li>Base model: 63.3%</li>
<li>Pre-pruned model: 64.2%</li>
<li>Post-pruned model: 64.2%</li>
</ul>
<p>The post-pruned model is the same as the pre-pruned’s. I will use the pre-pruned model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot tree</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(highest.cred.level.model.preprune, <span class="at">nn =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_post_secondary_paths_CART_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="main-takeaway-1" class="level2">
<h2 class="anchored" data-anchor-id="main-takeaway-1"><strong>Main Takeaway</strong></h2>
<p><strong>Model Performance</strong><br>
The pre-pruned tree achieved <strong>64.2% accuracy</strong> with a root node error of <strong>45.9%</strong>. Compared to the baseline distribution (where over half of students did not graduate postsecondary), the model provides a meaningful improvement in classification and highlights the central role of academic readiness and background factors in determining highest credential earned.</p>
<p><strong>Key Predictors</strong><br>
The most influential predictors retained after pruning were:</p>
<ul>
<li><strong>MCA Reading (MCA.R)</strong></li>
<li><strong>ACT Composite Score</strong></li>
<li><strong>Economic Status</strong></li>
<li><strong>PSEO Participation</strong></li>
<li><strong>Race/Ethnicity</strong></li>
<li><strong>Total CTE Courses Taken</strong></li>
</ul>
<p><strong>Interpretation of Tree Structure</strong><br>
Earning a <strong>bachelor’s degree or higher</strong> was most strongly associated with <strong>higher MCA Reading scores (≥4)</strong> and <strong>ACT Composite scores (≥22)</strong>, particularly for <strong>White and Asian/PI students</strong>. Within this group, advantaged students and those who participated in <strong>PSEO</strong> were especially likely to complete at the bachelor’s level or above.</p>
<p>By contrast, students with <strong>low MCA Reading scores</strong> or <strong>ACT scores below 19</strong> were overwhelmingly likely to <strong>not graduate postsecondary</strong>, regardless of other characteristics. Even among students with moderate ACT performance, <strong>fewer CTE courses</strong> was a marker of higher non-completion risk.</p>
<p>Notably, <strong>economic disadvantage</strong> tempered bachelor’s attainment. High scorers who were also low-income were less likely to reach a bachelor’s or higher compared to their more advantaged peers, highlighting persistent inequities in access to advanced credentials.</p>
<p><strong>Summary</strong><br>
The CART model shows that <strong>academic readiness is the primary gateway to bachelor’s and higher attainment</strong>, while <strong>low academic performance almost guarantees non-completion</strong>. CTE engagement, while generally positive for regional workforce outcomes, was not as strong a driver toward higher credentials—underscoring its role in anchoring students to sub-baccalaureate pathways. Meanwhile, race/ethnicity and economic status continue to stratify opportunities, even among academically prepared students.</p>
<p><strong>Policy Implications</strong><br>
Strengthening Southern MN’s workforce requires a dual focus:</p>
<ol type="1">
<li><strong>Bolster completion among moderate scorers and disadvantaged students</strong> by expanding academic supports, affordability measures, and targeted advising to reduce non-completion.</li>
<li><strong>Improve equity at the bachelor’s+ level</strong> by ensuring that high-achieving, low-income, and underrepresented minority students have the resources and pathways to reach advanced credentials.</li>
<li><strong>Leverage CTE as a stabilizer</strong>, but pair it with stackable credential opportunities so students anchored locally are not limited to sub-associate outcomes.</li>
</ol>
<p>In short, <strong>academic readiness remains the strongest predictor of highest credential level</strong>, but without targeted interventions, structural inequities in race and economic status continue to limit who attains bachelor’s and higher degrees.</p>
<p><br></p>
</section>
</section>
<section id="grand-synthesis-predictive-elements-of-postsecondary-pathways" class="level1">
<h1><strong>Grand Synthesis: Predictive Elements of Postsecondary Pathways</strong></h1>
<section id="overall-model-performance" class="level2">
<h2 class="anchored" data-anchor-id="overall-model-performance"><strong>Overall Model Performance</strong></h2>
<p>Across both dependent variables — <strong>postsecondary graduation location</strong> and <strong>highest credential earned</strong> — the pre-pruned CART models achieved accuracies of <strong>61.7%</strong> and <strong>64.2%</strong>, respectively. Both represented clear improvements over baseline distributions and showed that a relatively small set of predictors consistently explains meaningful variation in student pathways.</p>
<p>While not capturing all individual-level complexity, these models highlight <strong>distinct sets of academic, demographic, and experiential variables</strong> that shape whether students remain anchored in the Southern MN workforce pipeline or pursue mobility pathways.</p>
</section>
<section id="key-predictors-across-models" class="level2">
<h2 class="anchored" data-anchor-id="key-predictors-across-models"><strong>Key Predictors Across Models</strong></h2>
<p>The following predictors emerged as the most consistently influential:</p>
<ul>
<li><strong>Academic readiness</strong>: MCA Reading and ACT Composite Score.</li>
<li><strong>Economic status</strong>: Persistent disadvantages for low-income students.</li>
<li><strong>Race/Ethnicity</strong>: White and Asian/PI students more likely to reach higher credentials; Black, AI, and Hispanic students more often concentrated in lower or incomplete outcomes.</li>
<li><strong>PSEO participation</strong>: Steers students toward bachelor’s+ and out-of-region completions.</li>
<li><strong>CTE engagement (courses taken)</strong>: Reinforces regional and sub-baccalaureate pathways.</li>
</ul>
<p>These predictors operate in <strong>two clear pipelines</strong> — one driving local attachment through sub-baccalaureate credentials, and one fostering mobility through advanced credentials.</p>
</section>
<section id="interpretation-of-pathways" class="level2">
<h2 class="anchored" data-anchor-id="interpretation-of-pathways"><strong>Interpretation of Pathways</strong></h2>
<section id="graduation-location-ps.grad.location" class="level3">
<h3 class="anchored" data-anchor-id="graduation-location-ps.grad.location">1. <strong>Graduation Location (ps.grad.location)</strong></h3>
<ul>
<li><strong>Regional completions</strong> clustered among <strong>economically disadvantaged students with moderate academic readiness</strong>.</li>
<li><strong>Non-completion</strong> was strongly tied to <strong>low ACT and MCA scores</strong>, often regardless of background.</li>
<li><strong>High academic readiness and PSEO participation</strong> predicted completions outside the region, fueling mobility pathways.</li>
</ul>
<p><strong>Implication</strong>: Regional institutions disproportionately serve disadvantaged students who achieve moderate readiness, while high scorers leave the region for completion.</p>
</section>
<section id="highest-credential-earned-highest.cred.level-1" class="level3">
<h3 class="anchored" data-anchor-id="highest-credential-earned-highest.cred.level-1">2. <strong>Highest Credential Earned (highest.cred.level)</strong></h3>
<ul>
<li><strong>Bachelor’s or higher</strong> credentials were most strongly linked to <strong>high MCA and ACT scores</strong>, advantaged status, and <strong>PSEO participation</strong>.</li>
<li><strong>Non-completion</strong> was almost guaranteed for students with low MCA Reading or ACT scores, even when other factors were favorable.</li>
<li><strong>Associate or lower credentials</strong> (though less prominent in the tree structure) align with CTE-heavy pathways, serving as stabilizers for the regional workforce.</li>
</ul>
<p><strong>Implication</strong>: Academic readiness acts as the primary gateway to bachelor’s+ attainment, but economic and racial inequities remain barriers, even among high scorers.</p>
</section>
</section>
<section id="synthesis-of-findings" class="level2">
<h2 class="anchored" data-anchor-id="synthesis-of-findings"><strong>Synthesis of Findings</strong></h2>
<p>Together, the models reinforce the existence of a <strong>dual-pipeline system</strong> in Southern Minnesota:</p>
<ol type="1">
<li><strong>Regional Workforce Pipeline</strong>
<ul>
<li>Driven by <strong>CTE engagement, associate-or-lower credentials, and regional completions</strong>.</li>
<li>Anchors students with <strong>economic disadvantage and moderate readiness</strong> into the local labor market.</li>
<li>Provides workforce stability but limits long-term mobility and earning potential.</li>
</ul></li>
<li><strong>Mobility Pipeline</strong>
<ul>
<li>Driven by <strong>academic rigor, bachelor’s+ attainment, PSEO participation, and out-of-region completions</strong>.</li>
<li>Attracts <strong>advantaged, high-scoring students</strong>, who are least likely to remain in the region after completion.</li>
<li>Fuels statewide and out-of-state labor markets more than the local workforce.</li>
</ul></li>
</ol>
</section>
<section id="policy-implications" class="level2">
<h2 class="anchored" data-anchor-id="policy-implications"><strong>Policy Implications</strong></h2>
<ul>
<li><strong>Strengthen regional anchors</strong>: Expand academic and financial supports for disadvantaged, moderate scorers to ensure successful completions in Southern MN institutions.</li>
<li><strong>Address inequities in bachelor’s+ attainment</strong>: Target resources for high-achieving but low-income and underrepresented students to reduce barriers to advanced credentials.</li>
<li><strong>Leverage CTE strategically</strong>: Maintain CTE as a stabilizer but ensure stackable pathways to prevent students from being locked into sub-associate outcomes.</li>
<li><strong>Engage high-achievers locally</strong>: Create incentives and career opportunities that connect PSEO participants and bachelor’s+ completers back to the region to mitigate brain drain.</li>
</ul>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion"><strong>Conclusion</strong></h2>
<p>The predictive analysis confirms that <strong>academic readiness, economic status, and experiential factors like PSEO and CTE are the primary levers shaping postsecondary pathways</strong>. These pathways, in turn, determine whether students are most likely to remain in the Southern MN workforce or pursue mobility.</p>
<p>Ultimately, the models illustrate a <strong>structural duality</strong>: disadvantaged students with modest preparation form the backbone of the regional workforce through 2-year and regional completions, while advantaged high scorers are systematically funneled into statewide mobility. Policy efforts must therefore balance <strong>supporting the regional anchor pipeline</strong> with <strong>developing mechanisms to retain or re-engage mobile students</strong> after higher attainment.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>